version: '3.8'
services:
  serviceregistry:
    image: 'kwabla/silasgahnbaserviceregistry:0.0.1'
    container_name: silasgahnbaserviceregistry
    ports:
      - '8761:8761'
  configserver:
    image: 'kwabla/configserver:0.0.1'
    container_name: configserver
    ports:
      - '9296:9296'
    environment:
      - EUREKA_SERVER_ADDRESS:http://serviceregistry:8761/eureka
    healthcheck:
      test: ["CMD","curl","-f","http://configserver:9296/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - serviceregistry
  cloudgateway:
    image: 'kwabla/apigateway:0.0.1'
    container_name: apigateway
    ports:
      - '9090:9090'
    environment:
      - EUREKA_SERVER_ADDRESS:http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      - configserver
   
  aggregate:
    image: 'kwabla/aggregateservice:0.0.1'
    container_name: aggregateservice
    ports:
      - '8082:8082'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_APPLICATION_NAME=aggregateservice
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:9296
    depends_on:
      - database
      - configserver

  nbastatistics:
    image: 'kwabla/nbaservice:0.0.1'
    container_name: nbaservice
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_APPLICATION_NAME=Player-Statistics
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:9296
    depends_on:
      - database
      - configserver


  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
